spring.application.name=SportManager

spring.datasource.url=jdbc:postgresql://localhost:5432/sportmanager
spring.datasource.username=postgres
spring.datasource.password=SportManager30

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true